services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: "vaadin"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5436:5432"